# Generated by Django 3.0.8 on 2020-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200801_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-pic.jpg', upload_to='profile-images'),
        ),
    ]
