# Generated by Django 3.0.8 on 2020-08-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200806_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
